name: Update database types

on:
  schedule:
    # sets the action to run daily. You can modify this to run the action more or less frequently
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.head_ref != 'supabot**'
    steps:
      - uses: lyqht/generate-supabase-db-types-github-action@main
        with:
          SUPABASE_REF_ID: ${{ secrets.SUPABASE_REF_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
          DB_PASSWORD: ''
          OUTPUT_PATH: src/types/database.ts
